services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knife
    ports:
      - "5432:5432"
    volumes:
      - knife_pg:/var/lib/postgresql/data

volumes:
  knife_pg:
